import React, { useState } from "react";
import Icon from "../playlists/Icon";

export default {
  title: "Component/Icon",
  component: Icon
};

const data = [
  { name: "themify-Italic", size: "20px", viewBoxWidth: "17" },
  { name: "themify-agenda", size: "20px", viewBoxWidth: "17" },
  { name: "themify-alarm-clock", size: "20px", viewBoxWidth: "17" },
  { name: "themify-alert", size: "20px", viewBoxWidth: "17" },
  { name: "themify-align-center", size: "20px", viewBoxWidth: "17" },
  { name: "themify-align-justify", size: "20px", viewBoxWidth: "17" },
  { name: "themify-align-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-align-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-anchor", size: "20px", viewBoxWidth: "17" },
  { name: "themify-android", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-double-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-double-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-double-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-double-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-angle-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-announcement", size: "20px", viewBoxWidth: "17" },
  { name: "themify-apple", size: "20px", viewBoxWidth: "17" },
  { name: "themify-archive", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-circle-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-circle-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-circle-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-circle-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-top-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-top-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrow", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrows-corner", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrows-horizontal", size: "20px", viewBoxWidth: "17" },
  { name: "themify-arrows-vertical", size: "20px", viewBoxWidth: "17" },
  { name: "themify-back-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-back-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bag", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bar-chart-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bar-chart", size: "20px", viewBoxWidth: "17" },
  { name: "themify-basketball", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bell", size: "20px", viewBoxWidth: "17" },
  { name: "themify-blackboard", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bolt-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bolt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-book", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bookmark-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-bookmark", size: "20px", viewBoxWidth: "17" },
  { name: "themify-briefcase", size: "20px", viewBoxWidth: "17" },
  { name: "themify-brush-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-brush", size: "20px", viewBoxWidth: "17" },
  { name: "themify-calendar", size: "20px", viewBoxWidth: "17" },
  { name: "themify-camera", size: "20px", viewBoxWidth: "17" },
  { name: "themify-car", size: "20px", viewBoxWidth: "17" },
  { name: "themify-check-box", size: "20px", viewBoxWidth: "17" },
  { name: "themify-check", size: "20px", viewBoxWidth: "17" },
  { name: "themify-clip", size: "20px", viewBoxWidth: "17" },
  { name: "themify-clipboard", size: "20px", viewBoxWidth: "17" },
  { name: "themify-close", size: "20px", viewBoxWidth: "17" },
  { name: "themify-cloud-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-cloud-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-cloud", size: "20px", viewBoxWidth: "17" },
  { name: "themify-comment-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-comment", size: "20px", viewBoxWidth: "17" },
  { name: "themify-comments-smiley", size: "20px", viewBoxWidth: "17" },
  { name: "themify-comments", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-backward", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-eject", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-forward", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-pause", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-play", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-record", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-shuffle", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-skip-backward", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-skip-forward", size: "20px", viewBoxWidth: "17" },
  { name: "themify-control-stop", size: "20px", viewBoxWidth: "17" },
  { name: "themify-credit-card", size: "20px", viewBoxWidth: "17" },
  { name: "themify-crown", size: "20px", viewBoxWidth: "17" },
  { name: "themify-css3", size: "20px", viewBoxWidth: "17" },
  { name: "themify-cup", size: "20px", viewBoxWidth: "17" },
  { name: "themify-cut", size: "20px", viewBoxWidth: "17" },
  { name: "themify-dashboard", size: "20px", viewBoxWidth: "17" },
  { name: "themify-desktop", size: "20px", viewBoxWidth: "17" },
  { name: "themify-direction-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-direction", size: "20px", viewBoxWidth: "17" },
  { name: "themify-download", size: "20px", viewBoxWidth: "17" },
  { name: "themify-dribbble", size: "20px", viewBoxWidth: "17" },
  { name: "themify-dropbox-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-dropbox", size: "20px", viewBoxWidth: "17" },
  { name: "themify-drupal", size: "20px", viewBoxWidth: "17" },
  { name: "themify-email", size: "20px", viewBoxWidth: "17" },
  { name: "themify-envelope", size: "20px", viewBoxWidth: "17" },
  { name: "themify-eraser", size: "20px", viewBoxWidth: "17" },
  { name: "themify-exchange-vertical", size: "20px", viewBoxWidth: "17" },
  { name: "themify-export", size: "20px", viewBoxWidth: "17" },
  { name: "themify-eye", size: "20px", viewBoxWidth: "17" },
  { name: "themify-face-sad", size: "20px", viewBoxWidth: "17" },
  { name: "themify-face-smile", size: "20px", viewBoxWidth: "17" },
  { name: "themify-facebook", size: "20px", viewBoxWidth: "17" },
  { name: "themify-file", size: "20px", viewBoxWidth: "17" },
  { name: "themify-files", size: "20px", viewBoxWidth: "17" },
  { name: "themify-filter", size: "20px", viewBoxWidth: "17" },
  { name: "themify-flag-alt-2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-flag-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-flag", size: "20px", viewBoxWidth: "17" },
  { name: "themify-flickr-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-flickr", size: "20px", viewBoxWidth: "17" },
  { name: "themify-folder", size: "20px", viewBoxWidth: "17" },
  { name: "themify-fullscreen", size: "20px", viewBoxWidth: "17" },
  { name: "themify-gallery", size: "20px", viewBoxWidth: "17" },
  { name: "themify-game", size: "20px", viewBoxWidth: "17" },
  { name: "themify-gift", size: "20px", viewBoxWidth: "17" },
  { name: "themify-github", size: "20px", viewBoxWidth: "17" },
  { name: "themify-google", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-drag", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-open", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-point-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-point-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-point-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-point-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hand-stop", size: "20px", viewBoxWidth: "17" },
  { name: "themify-harddrive", size: "20px", viewBoxWidth: "17" },
  { name: "themify-harddrives", size: "20px", viewBoxWidth: "17" },
  { name: "themify-headphone-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-headphone", size: "20px", viewBoxWidth: "17" },
  { name: "themify-heart-broken", size: "20px", viewBoxWidth: "17" },
  { name: "themify-heart", size: "20px", viewBoxWidth: "17" },
  { name: "themify-help-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-help", size: "20px", viewBoxWidth: "17" },
  { name: "themify-home", size: "20px", viewBoxWidth: "17" },
  { name: "themify-html5", size: "20px", viewBoxWidth: "17" },
  { name: "themify-hummer", size: "20px", viewBoxWidth: "17" },
  { name: "themify-id-badge", size: "20px", viewBoxWidth: "17" },
  { name: "themify-image", size: "20px", viewBoxWidth: "17" },
  { name: "themify-import", size: "20px", viewBoxWidth: "17" },
  { name: "themify-infinite", size: "20px", viewBoxWidth: "17" },
  { name: "themify-info-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-info", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ink-pen", size: "20px", viewBoxWidth: "17" },
  { name: "themify-instagram", size: "20px", viewBoxWidth: "17" },
  { name: "themify-joomla", size: "20px", viewBoxWidth: "17" },
  { name: "themify-jsfiddle", size: "20px", viewBoxWidth: "17" },
  { name: "themify-key", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layers-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layers", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-accordion-list", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-accordion-merged", size: "20px", viewBoxWidth: "17" },
  {
    name: "themify-layout-accordion-separated",
    size: "20px",
    viewBoxWidth: "17"
  },
  { name: "themify-layout-column2-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-column2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-column3", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-column4-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-column4", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-cta-btn-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-cta-btn-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-cta-center", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-cta-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-cta-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid2-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid2-thumb", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid3-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid3", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid4-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-grid4", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-line-solid", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-list-large-image", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-list-post", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-list-thumb-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-list-thumb", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-center-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-center", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-left-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-left", size: "20px", viewBoxWidth: "17" },
  {
    name: "themify-layout-media-overlay-alt-2",
    size: "20px",
    viewBoxWidth: "17"
  },
  {
    name: "themify-layout-media-overlay-alt",
    size: "20px",
    viewBoxWidth: "17"
  },
  { name: "themify-layout-media-overlay", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-right-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-media-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-menu-full", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-menu-separated", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-menu-v", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-menu", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-placeholder", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-sidebar-2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-sidebar-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-sidebar-none", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-sidebar-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-slider-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-slider", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-tab-min", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-tab-v", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-tab-window", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-tab", size: "20px", viewBoxWidth: "17" },
  {
    name: "themify-layout-width-default-alt",
    size: "20px",
    viewBoxWidth: "17"
  },
  { name: "themify-layout-width-default", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout-width-full", size: "20px", viewBoxWidth: "17" },
  { name: "themify-layout", size: "20px", viewBoxWidth: "17" },
  { name: "themify-light-bulb", size: "20px", viewBoxWidth: "17" },
  { name: "themify-line-dashed", size: "20px", viewBoxWidth: "17" },
  { name: "themify-line-dotted", size: "20px", viewBoxWidth: "17" },
  { name: "themify-line-double", size: "20px", viewBoxWidth: "17" },
  { name: "themify-link", size: "20px", viewBoxWidth: "17" },
  { name: "themify-linkedin", size: "20px", viewBoxWidth: "17" },
  { name: "themify-linux", size: "20px", viewBoxWidth: "17" },
  { name: "themify-list-ol", size: "20px", viewBoxWidth: "17" },
  { name: "themify-list", size: "20px", viewBoxWidth: "17" },
  { name: "themify-location-arrow", size: "20px", viewBoxWidth: "17" },
  { name: "themify-location-pin", size: "20px", viewBoxWidth: "17" },
  { name: "themify-lock", size: "20px", viewBoxWidth: "17" },
  { name: "themify-loop", size: "20px", viewBoxWidth: "17" },
  { name: "themify-magnet", size: "20px", viewBoxWidth: "17" },
  { name: "themify-map-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-map", size: "20px", viewBoxWidth: "17" },
  { name: "themify-marker-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-marker", size: "20px", viewBoxWidth: "17" },
  { name: "themify-medall-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-medall", size: "20px", viewBoxWidth: "17" },
  { name: "themify-menu-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-menu", size: "20px", viewBoxWidth: "17" },
  { name: "themify-microphone-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-microphone", size: "20px", viewBoxWidth: "17" },
  { name: "themify-microsoft-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-microsoft", size: "20px", viewBoxWidth: "17" },
  { name: "themify-minus", size: "20px", viewBoxWidth: "17" },
  { name: "themify-mobile", size: "20px", viewBoxWidth: "17" },
  { name: "themify-money", size: "20px", viewBoxWidth: "17" },
  { name: "themify-more-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-more", size: "20px", viewBoxWidth: "17" },
  { name: "themify-mouse-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-mouse", size: "20px", viewBoxWidth: "17" },
  { name: "themify-music", size: "20px", viewBoxWidth: "17" },
  { name: "themify-na", size: "20px", viewBoxWidth: "17" },
  { name: "themify-new-window", size: "20px", viewBoxWidth: "17" },
  { name: "themify-notepad", size: "20px", viewBoxWidth: "17" },
  { name: "themify-package", size: "20px", viewBoxWidth: "17" },
  { name: "themify-paint-bucket", size: "20px", viewBoxWidth: "17" },
  { name: "themify-paint-roller", size: "20px", viewBoxWidth: "17" },
  { name: "themify-palette", size: "20px", viewBoxWidth: "17" },
  { name: "themify-panel", size: "20px", viewBoxWidth: "17" },
  { name: "themify-paragraph", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pencil-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pencil-alt2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pencil", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pie-chart", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pin-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pin", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pin2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pinterest", size: "20px", viewBoxWidth: "17" },
  { name: "themify-plug", size: "20px", viewBoxWidth: "17" },
  { name: "themify-plus", size: "20px", viewBoxWidth: "17" },
  { name: "themify-power-off", size: "20px", viewBoxWidth: "17" },
  { name: "themify-printer", size: "20px", viewBoxWidth: "17" },
  { name: "themify-pulse", size: "20px", viewBoxWidth: "17" },
  { name: "themify-quote-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-quote-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-receipt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-reddit", size: "20px", viewBoxWidth: "17" },
  { name: "themify-reload", size: "20px", viewBoxWidth: "17" },
  { name: "themify-rocket", size: "20px", viewBoxWidth: "17" },
  { name: "themify-rss-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-rss", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ruler-alt-2", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ruler-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ruler-pencil", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ruler", size: "20px", viewBoxWidth: "17" },
  { name: "themify-save-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-save", size: "20px", viewBoxWidth: "17" },
  { name: "themify-server", size: "20px", viewBoxWidth: "17" },
  { name: "themify-settings", size: "20px", viewBoxWidth: "17" },
  { name: "themify-share-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-share", size: "20px", viewBoxWidth: "17" },
  { name: "themify-sharethis-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-sharethis", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shield", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shift-left-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shift-left", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shift-right-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shift-right", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shine", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shopping-cart-full", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shopping-cart", size: "20px", viewBoxWidth: "17" },
  { name: "themify-shortcode", size: "20px", viewBoxWidth: "17" },
  { name: "themify-signal", size: "20px", viewBoxWidth: "17" },
  { name: "themify-skype", size: "20px", viewBoxWidth: "17" },
  { name: "themify-slice", size: "20px", viewBoxWidth: "17" },
  { name: "themify-smallcap", size: "20px", viewBoxWidth: "17" },
  { name: "themify-soundcloud", size: "20px", viewBoxWidth: "17" },
  { name: "themify-split-h", size: "20px", viewBoxWidth: "17" },
  { name: "themify-split-v-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-split-v", size: "20px", viewBoxWidth: "17" },
  { name: "themify-spray", size: "20px", viewBoxWidth: "17" },
  { name: "themify-stack-overflow", size: "20px", viewBoxWidth: "17" },
  { name: "themify-stamp", size: "20px", viewBoxWidth: "17" },
  { name: "themify-star", size: "20px", viewBoxWidth: "17" },
  { name: "themify-stats-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-stats-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-support", size: "20px", viewBoxWidth: "17" },
  { name: "themify-tablet", size: "20px", viewBoxWidth: "17" },
  { name: "themify-tag", size: "20px", viewBoxWidth: "17" },
  { name: "themify-target", size: "20px", viewBoxWidth: "17" },
  { name: "themify-text", size: "20px", viewBoxWidth: "17" },
  { name: "themify-themify-favicon-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-themify-favicon", size: "20px", viewBoxWidth: "17" },
  { name: "themify-themify-logo", size: "20px", viewBoxWidth: "17" },
  { name: "themify-thought", size: "20px", viewBoxWidth: "17" },
  { name: "themify-thumb-down", size: "20px", viewBoxWidth: "17" },
  { name: "themify-thumb-up", size: "20px", viewBoxWidth: "17" },
  { name: "themify-ticket", size: "20px", viewBoxWidth: "17" },
  { name: "themify-time", size: "20px", viewBoxWidth: "17" },
  { name: "themify-timer", size: "20px", viewBoxWidth: "17" },
  { name: "themify-trash", size: "20px", viewBoxWidth: "17" },
  { name: "themify-trello", size: "20px", viewBoxWidth: "17" },
  { name: "themify-truck", size: "20px", viewBoxWidth: "17" },
  { name: "themify-tumblr-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-tumblr", size: "20px", viewBoxWidth: "17" },
  { name: "themify-twitter-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-twitter", size: "20px", viewBoxWidth: "17" },
  { name: "themify-unlink", size: "20px", viewBoxWidth: "17" },
  { name: "themify-unlock", size: "20px", viewBoxWidth: "17" },
  { name: "themify-upload", size: "20px", viewBoxWidth: "17" },
  { name: "themify-uppercase", size: "20px", viewBoxWidth: "17" },
  { name: "themify-user", size: "20px", viewBoxWidth: "17" },
  { name: "themify-vector", size: "20px", viewBoxWidth: "17" },
  { name: "themify-video-camera", size: "20px", viewBoxWidth: "17" },
  { name: "themify-video-clapper", size: "20px", viewBoxWidth: "17" },
  { name: "themify-view-grid", size: "20px", viewBoxWidth: "17" },
  { name: "themify-view-list", size: "20px", viewBoxWidth: "17" },
  { name: "themify-vimeo-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-vimeo", size: "20px", viewBoxWidth: "17" },
  { name: "themify-volume", size: "20px", viewBoxWidth: "17" },
  { name: "themify-wallet", size: "20px", viewBoxWidth: "17" },
  { name: "themify-wand", size: "20px", viewBoxWidth: "17" },
  { name: "themify-wheelchair", size: "20px", viewBoxWidth: "17" },
  { name: "themify-widget-alt", size: "20px", viewBoxWidth: "17" },
  { name: "themify-widget", size: "20px", viewBoxWidth: "17" },
  { name: "themify-widgetized", size: "20px", viewBoxWidth: "17" },
  { name: "themify-window", size: "20px", viewBoxWidth: "17" },
  { name: "themify-wordpress", size: "20px", viewBoxWidth: "17" },
  { name: "themify-world", size: "20px", viewBoxWidth: "17" },
  { name: "themify-write", size: "20px", viewBoxWidth: "17" },
  { name: "themify-yahoo", size: "20px", viewBoxWidth: "17" },
  { name: "themify-youtube", size: "20px", viewBoxWidth: "17" },
  { name: "themify-zip", size: "20px", viewBoxWidth: "17" },
  { name: "themify-zoom-in", size: "20px", viewBoxWidth: "17" },
  { name: "themify-zoom-out", size: "20px", viewBoxWidth: "17" }
];

export const basic = () => {
  const Icons = data.map((item, i) => {
    return (
      <Icon
        size={item.size}
        name={item.name}
        viewBoxWidth={item.viewBoxWidth}
      />
    );
  });
  return <>{Icons}</>;
};
